### ISSUE TITLE
Footer/Legal Info

### ISSUE THREAD

**Issue by chrrel** [fl0cke/virus_foerdert_viren#2]
Gut wäre eine Fußzeile für die Seite in dem wir die üblichen Links unterbringen können. Z.B

`Über uns | Impressum | Datenschutz`

**Comment by Sn0wfreezeDev** [comment]
Links sind drin, aber uns fehlt noch der Inhalt

**Comment by chrrel** [comment]
Habe Vorlagen eingefügt. Es fehlen noch ein paar Details.
